### ISSUE TITLE
Add the faucet to the docker-compose setup

### ISSUE THREAD

**Issue by metachris** [neoauth/neo-local#14]
Would be great to add the faucet to this setup. Would be very useful for workshops.

https://github.com/CityOfZion/neo-faucet

**Comment by jeroenptrs** [comment]
@metachris great idea! I'm looking at the neo-faucet setup right now, I think the first thing we could do is update the dependencies to the new neo-python and neo-boa versions? Will that break things?

Next up is where to put it. I'm thinking it needs to be dockerized as well then?

**Comment by metachris** [comment]
moved to https://github.com/CityOfZion/neo-local/issues/6

cc/ @jeroenptrs
