### ISSUE TITLE
[neo-local] Waiting for network......... takes a looong time

### ISSUE THREAD

**Issue by metachris** [neoauth/neo-local#20]
When running `make start`, the step which shows `[neo-local] Waiting for network...................` takes too long, like 2 minutes or even more. Why is that? Doesn't seem necessary. The original privnet container starts immediately, so does neo-python.

**Comment by revett** [comment]
This is one of the bash scripts waiting for the **neoscan** container to come online.

See here for context: https://github.com/neoauth/neo-local/blob/0714b9b382d3c6076423a0f58c86d32b7044b916/scripts/ping.sh#L1-L9

I think adding better documentation here would be a good fix so the user understands what they are waiting for and the expected time.

Thoughts?

**Comment by metachris** [comment]
@revett can you please replicate this comment here: https://github.com/CityOfZion/neo-local/issues/4

PS: Perhaps it should not be blocking for so long until neoscan is up, since all the rest is up a minute earlier already?
