### ISSUE TITLE
When i run `make start` and exit neo-py and run `make start` again it will wipe things

### ISSUE THREAD

**Issue by metachris** [neoauth/neo-local#21]
I think it would be more useful to warn users // ask if they really want to remove the old containers or simply reconnect.

**Comment by metachris** [comment]
I think a better development workflow would be to provide a simple way to start all the services, and then attach to it, so just renaming things.

* `make start` should start the containers
* `make attach` should attach to the neo-python prompt

**Comment by revett** [comment]
Yup this would be a really nice addition.

`make start` should be _smart_ enough to work out if there are containers already running and then give the user the option to remove them or not.

**Comment by metachris** [comment]
https://github.com/CityOfZion/neo-local/issues/3
