### ISSUE TITLE
Document usage on Windows

### ISSUE THREAD

**Issue by metachris** [neoauth/neo-local#22]
How can I use this on Windows? Add some documentation. There is no reason that shouldn't be possible -- Docker works just fine, and a lot of devs actually use Windows.

So I think documentation on how to get the setup up and running on Windows is quite critical to reach the full potential of this setup.

**Comment by revett** [comment]
I agree 💯

Is there a `make`equivalent for Windows?

**Comment by metachris** [comment]
https://github.com/CityOfZion/neo-local/issues/2
